name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Detekt
      run: ./gradlew detekt
    - name: Get release keystore
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" >> release.keystore.asc
        echo "${{ secrets.KEYSTORE_PROPERTIES }}" >> keystore-properties.txt.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > keystore.jks
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch keystore-properties.txt.asc > keystore-properties.txt
        ls -la
        
    - name: Build with Gradle
      run: |
        ./gradlew :app:assembleRelease
        ./scripts/prepareRelease.sh
        ls -la

